debug: True
#---------------------------------------
#Declare host and port
#-------------------------------------
host: "192.168.1.2"
port: 5012
https: False
host_dir: '/'
name: file explorer
description: This is a application for file explorer
#------------------------------------------
# Specify template folder
#------------------------------------------------
template_folder: templates
static: C:/code/python/dj/jd-apps/app_manager/static
static_url: /static
