
debug: true
description: Create congfig.yaml and mappall quicky.config.Congfig attr to congfig.yaml
host_: 172.16.9.78
host: 192.168.1.2
binding: 0.0.0.0
#host: 192.168.1.2
host_dir: /
https: false
name: Noname
port: 5432
template_folder: templates
media:
  streaming_buffering_in_KB: 32 # Tuy theo dung luong RAM cua server va chat luong video can ho tro vi du chat luong 4k
                                # 8*4=32
  streaming_segment_size_in_KB: 0 # Bang 0 la khong gioi han. Truong hop khong gioi neu host tren iis voi
                                  # fastcgi thi vao thu muc C:\Windows\System32\inetsrv\config
                                  # file applicationHost.config the fastCgi
                                  # signalBeforeTerminateSeconds="30"  activityTimeout="60000" requestTimeout="60000" instanceMaxRequests="1000000"
                                  # Voi cac server khong du manh thi nen gioi han ()